 # Psyduck stack
services:
  psyduck-schema-setup:
    build:
      context: .
      dockerfile: database.Dockerfile
    depends_on:
      - psyduck-db

  psyduck-db:
    image: mariadb:latest
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password --binlog-expire-logs-seconds=86400
    container_name: psyduck-db
    ports: 
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: psyyypsyyyyyyyduck
      MYSQL_DATABASE: psyduck
      MYSQL_USER: IamPsyduck
      MYSQL_PASSWORD: thebestpsyduck
    volumes:
      - ./mysql_data/mariadb.cnf:/etc/mysql/mariadb.cnf
      - ./mysql_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

  psyduck-redis:
    image: redis:latest
    restart: unless-stopped
    container_name: psyduck-redis
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"

  psyduck-celery:
    container_name: psyduck-celery
    depends_on:
      - database
      - psyduck-redis
    build:
      context: .
      dockerfile: celery.Dockerfile
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro

  psyduck-webhook:
    container_name: psyduck-webhook
    depends_on:
      - psyduck-redis
    build:
      context: .
      dockerfile: webhook.Dockerfile
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro

  # API to provide parsed data
  # Default container port 5001

  psyduck-api:
    container_name: psyduck-api
    depends_on:
      - psyduck-redis
    build:
      context: .
      dockerfile: api.Dockerfile
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /etc/localtime:/etc/localtime:ro
