from config.app_config import app_config
from tortoise import run_async
from orm.procedures import ProcedureGenerator
from orm.events import EventGenerator
from orm.queries import DatabaseOperations

async def create_procedures():
    db_ops = DatabaseOperations()
    procedure_generator = ProcedureGenerator()
    area_timezones = await db_ops.get_area_timezones()

    timezone_groups = {}
    for area in area_timezones:
        area_name, offset = area
        if offset not in timezone_groups:
            timezone_groups[offset] = []
        timezone_groups[offset].append(area_name)

    for offset, areas in timezone_groups.items():
        drop_store_pokemon_total_sql, store_pokemon_total_sql = await procedure_generator.generate_store_pokemon_total_sql(areas, offset)
        drop_store_pokemon_grouped_sql, store_pokemon_grouped_sql = await procedure_generator.generate_store_pokemon_grouped_sql(areas, offset)
        drop_store_quest_total_sql, store_quest_total_sql = await procedure_generator.generate_store_quest_total_sql(areas, offset)
        drop_store_quest_grouped_sql, store_quest_grouped_sql = await procedure_generator.generate_store_quest_grouped_sql(areas, offset)
        drop_store_raid_total_sql, store_raid_total_sql = await procedure_generator.generate_store_raid_total_sql(areas, offset)
        drop_store_raid_grouped_sql, store_raid_grouped_sql = await procedure_generator.generate_store_raid_grouped_sql(areas, offset)
        drop_store_invasion_total_sql, store_invasion_total_sql = await procedure_generator.generate_store_invasion_total_sql(areas, offset)
        drop_store_invasion_grouped_sql, store_invasion_grouped_sql = await procedure_generator.generate_store_invasion_grouped_sql(areas, offset)
        drop_store_hourly_pokemon_tth_sql, store_hourly_pokemon_tth_sql = await procedure_generator.generate_store_hourly_pokemon_tth_procedure()
        drop_update_hourly_pokemon_total_sql, update_hourly_pokemon_total_sql = await procedure_generator.generate_update_hourly_pokemon_total_procedure()
        drop_update_daily_pokemon_total_sql, update_daily_pokemon_total_sql = await procedure_generator.generate_update_daily_pokemon_total_procedure(areas, offset)
        drop_update_total_pokemon_total_sql, update_total_pokemon_total_sql = await procedure_generator.generate_update_total_pokemon_total_procedure(areas, offset)
        drop_update_daily_pokemon_grouped_sql, update_daily_pokemon_grouped_sql = await procedure_generator.generate_update_daily_pokemon_grouped_procedure(areas, offset)
        drop_update_weekly_pokemon_grouped_sql, update_weekly_pokemon_grouped_sql = await procedure_generator.generate_update_weekly_pokemon_grouped_procedure(areas, offset)
        drop_udpate_monthly_pokemon_grouped_sql, udpate_monthly_pokemon_grouped_sql = await procedure_generator.generate_udpate_monthly_pokemon_grouped_procedure(areas, offset)
        drop_update_daily_quest_total_sql, update_daily_quest_total_sql = await procedure_generator.generate_update_daily_quest_total_procedure(areas, offset)
        drop_update_total_quest_total_sql, update_total_quest_total_sql = await procedure_generator.generate_update_total_quest_total_procedure(areas, offset)
        drop_update_daily_quest_grouped_sql, update_daily_quest_grouped_sql = await procedure_generator.generate_update_daily_quest_grouped_procedure(areas, offset)
        drop_update_weekly_quest_grouped_sql, update_weekly_quest_grouped_sql = await procedure_generator.generate_update_weekly_quest_grouped_procedure(areas, offset)
        drop_update_monthly_quest_grouped_sql, update_monthly_quest_grouped_sql = await procedure_generator.generate_update_monthly_quest_grouped_procedure(areas, offset)
        drop_update_hourly_raid_total_sql, update_hourly_raid_total_sql = await procedure_generator.generate_update_hourly_raid_total_procedure()
        drop_update_daily_raid_total_sql, update_daily_raid_total_sql = await procedure_generator.generate_update_daily_raid_total_procedure(areas, offset)
        drop_update_total_raid_total_sql, update_total_raid_total_sql = await procedure_generator.generate_update_total_raid_total_procedure(areas, offset)
        drop_update_daily_raid_grouped_sql, update_daily_raid_grouped_sql = await procedure_generator.generate_update_daily_raid_grouped_procedure(areas, offset)
        drop_update_weekly_raid_grouped_sql, update_weekly_raid_grouped_sql = await procedure_generator.generate_update_weekly_raid_grouped_procedure(areas, offset)
        drop_update_monthly_raid_grouped_sql, update_monthly_raid_grouped_sql = await procedure_generator.generate_update_monthly_raid_grouped_procedure(areas, offset)
        drop_update_hourly_invasion_total_sql, update_hourly_invasion_total_sql = await procedure_generator.generate_update_hourly_invasion_total_procedure()
        drop_update_daily_invasion_total_sql, update_daily_invasion_total_sql = await procedure_generator.generate_update_daily_invasion_total_procedure(areas, offset)
        drop_update_total_invasion_total_sql, update_total_invasion_total_sql = await procedure_generator.generate_update_total_invasion_total_procedure(areas, offset)
        drop_update_daily_invasion_grouped_sql, update_daily_invasion_grouped_sql = await procedure_generator.generate_update_daily_invasion_grouped_procedure(areas, offset)
        drop_update_weekly_invasion_grouped_sql, update_weekly_invasion_grouped_sql = await procedure_generator.generate_update_weekly_invasion_grouped_procedure(areas, offset)
        drop_update_monthly_invasion_grouped_sql, update_monthly_invasion_grouped_sql = await procedure_generator.generate_update_monthly_invasion_grouped_procedure(areas, offset)
        drop_update_hourly_surge_sql, update_hourly_surge_sql = await procedure_generator.generate_update_hourly_surge_procedure()
        drop_update_daily_surge_sql, update_daily_surge_sql = await procedure_generator.generate_update_daily_surge_procedure()
        drop_update_weekly_surge_sql, update_weekly_surge_sql = await procedure_generator.generate_update_weekly_surge_procedure()
        drop_update_monthly_surge_sql, update_monthly_surge_sql = await procedure_generator.generate_update_monthly_surge_procedure()
        drop_update_hourly_pokemon_tth_sql, update_hourly_pokemon_tth_sql = await procedure_generator.generate_update_hourly_pokemon_tth_procedure()
        drop_update_daily_pokemon_tth_sql, update_daily_pokemon_tth_sql = await procedure_generator.generate_update_daily_pokemon_tth_procedure(areas, offset)
        drop_clean_pokemon_sightings_sql, clean_pokemon_sightings_sql = await procedure_generator.generate_clean_pokemon_sightings_procedure(areas, offset)
        drop_clean_quest_sightings_sql, clean_quest_sightings_sql = await procedure_generator.generate_clean_quest_sightings_procedure(areas, offset)
        drop_clean_raid_sightings_sql, clean_raid_sightings_sql = await procedure_generator.generate_clean_raid_sightings_procedure(areas, offset)
        drop_clean_invasion_sightigns_sql, clean_invasion_sightigns_sql = await procedure_generator.generate_clean_invasion_sightigns_procedure(areas, offset)

        await db_ops.execute_sql(drop_store_pokemon_total_sql)
        await db_ops.execute_sql(store_pokemon_total_sql)
        await db_ops.execute_sql(drop_store_pokemon_grouped_sql)
        await db_ops.execute_sql(store_pokemon_grouped_sql)
        await db_ops.execute_sql(drop_store_quest_total_sql)
        await db_ops.execute_sql(store_quest_total_sql)
        await db_ops.execute_sql(drop_store_quest_grouped_sql)
        await db_ops.execute_sql(store_quest_grouped_sql)
        await db_ops.execute_sql(drop_store_raid_total_sql)
        await db_ops.execute_sql(store_raid_total_sql)
        await db_ops.execute_sql(drop_store_raid_grouped_sql)
        await db_ops.execute_sql(store_raid_grouped_sql)
        await db_ops.execute_sql(drop_store_invasion_total_sql)
        await db_ops.execute_sql(store_invasion_total_sql)
        await db_ops.execute_sql(drop_store_invasion_grouped_sql)
        await db_ops.execute_sql(store_invasion_grouped_sql)
        await db_ops.execute_sql(drop_store_hourly_pokemon_tth_sql)
        await db_ops.execute_sql(store_hourly_pokemon_tth_sql)
        await db_ops.execute_sql(drop_update_hourly_pokemon_total_sql)
        await db_ops.execute_sql(update_hourly_pokemon_total_sql)
        await db_ops.execute_sql(drop_update_daily_pokemon_total_sql)
        await db_ops.execute_sql(update_daily_pokemon_total_sql)
        await db_ops.execute_sql(drop_update_total_pokemon_total_sql)
        await db_ops.execute_sql(update_total_pokemon_total_sql)
        await db_ops.execute_sql(drop_update_daily_pokemon_grouped_sql)
        await db_ops.execute_sql(update_daily_pokemon_grouped_sql)
        await db_ops.execute_sql(drop_update_weekly_pokemon_grouped_sql)
        await db_ops.execute_sql(update_weekly_pokemon_grouped_sql)
        await db_ops.execute_sql(drop_udpate_monthly_pokemon_grouped_sql)
        await db_ops.execute_sql(udpate_monthly_pokemon_grouped_sql)
        await db_ops.execute_sql(drop_update_daily_quest_total_sql)
        await db_ops.execute_sql(update_daily_quest_total_sql)
        await db_ops.execute_sql(drop_update_total_quest_total_sql)
        await db_ops.execute_sql(update_total_quest_total_sql)
        await db_ops.execute_sql(drop_update_daily_quest_grouped_sql)
        await db_ops.execute_sql(update_daily_quest_grouped_sql)
        await db_ops.execute_sql(drop_update_weekly_quest_grouped_sql)
        await db_ops.execute_sql(update_weekly_quest_grouped_sql)
        await db_ops.execute_sql(drop_update_monthly_quest_grouped_sql)
        await db_ops.execute_sql(update_monthly_quest_grouped_sql)
        await db_ops.execute_sql(drop_update_hourly_raid_total_sql)
        await db_ops.execute_sql(update_hourly_raid_total_sql)
        await db_ops.execute_sql(drop_update_daily_raid_total_sql)
        await db_ops.execute_sql(update_daily_raid_total_sql)
        await db_ops.execute_sql(drop_update_total_raid_total_sql)
        await db_ops.execute_sql(update_total_raid_total_sql)
        await db_ops.execute_sql(drop_update_daily_raid_grouped_sql)
        await db_ops.execute_sql(update_daily_raid_grouped_sql)
        await db_ops.execute_sql(drop_update_weekly_raid_grouped_sql)
        await db_ops.execute_sql(update_weekly_raid_grouped_sql)
        await db_ops.execute_sql(drop_update_monthly_raid_grouped_sql)
        await db_ops.execute_sql(update_monthly_raid_grouped_sql)
        await db_ops.execute_sql(drop_update_hourly_invasion_total_sql)
        await db_ops.execute_sql(update_hourly_invasion_total_sql)
        await db_ops.execute_sql(drop_update_daily_invasion_total_sql)
        await db_ops.execute_sql(update_daily_invasion_total_sql)
        await db_ops.execute_sql(drop_update_total_invasion_total_sql)
        await db_ops.execute_sql(update_total_invasion_total_sql)
        await db_ops.execute_sql(drop_update_daily_invasion_grouped_sql)
        await db_ops.execute_sql(update_daily_invasion_grouped_sql)
        await db_ops.execute_sql(drop_update_weekly_invasion_grouped_sql)
        await db_ops.execute_sql(update_weekly_invasion_grouped_sql)
        await db_ops.execute_sql(drop_update_monthly_invasion_grouped_sql)
        await db_ops.execute_sql(update_monthly_invasion_grouped_sql)
        await db_ops.execute_sql(drop_update_hourly_surge_sql)
        await db_ops.execute_sql(update_hourly_surge_sql)
        await db_ops.execute_sql(drop_update_daily_surge_sql)
        await db_ops.execute_sql(update_daily_surge_sql)
        await db_ops.execute_sql(drop_update_weekly_surge_sql)
        await db_ops.execute_sql(update_weekly_surge_sql)
        await db_ops.execute_sql(drop_update_monthly_surge_sql)
        await db_ops.execute_sql(update_monthly_surge_sql)
        await db_ops.execute_sql(drop_update_hourly_pokemon_tth_sql)
        await db_ops.execute_sql(update_hourly_pokemon_tth_sql)
        await db_ops.execute_sql(drop_update_daily_pokemon_tth_sql)
        await db_ops.execute_sql(update_daily_pokemon_tth_sql)
        await db_ops.execute_sql(drop_clean_pokemon_sightings_sql)
        await db_ops.execute_sql(clean_pokemon_sightings_sql)
        await db_ops.execute_sql(drop_clean_quest_sightings_sql)
        await db_ops.execute_sql(clean_quest_sightings_sql)
        await db_ops.execute_sql(drop_clean_raid_sightings_sql)
        await db_ops.execute_sql(clean_raid_sightings_sql)
        await db_ops.execute_sql(drop_clean_invasion_sightigns_sql)
        await db_ops.execute_sql(clean_invasion_sightigns_sql)

async def main():
    # Create procedures
    await create_procedures()

    # Create events
    event_generator = EventGenerator()
    await event_generator.create_events()

if __name__ == "__main__":
    run_async(main())
